Service specified rollback.

diff --git a/.github/workflows/cd.yaml b/.github/workflows/cd.yaml
--- a/.github/workflows/cd.yaml
+++ b/.github/workflows/cd.yaml
@@ -87,23 +87,34 @@ jobs:
         run: |
           kustomize build ./k8s/overlays/staging | kubectl apply -f -
 
-      # Step 14: Check the deployment status for all services
+      # Step 14: Check the deployment status for each service
       - name: Check Rollout Status
         run: |
-          kubectl rollout status deployment/notification-service --timeout=10m
-          kubectl rollout status deployment/user-service --timeout=10m
-          kubectl rollout status deployment/watchlist-service --timeout=10m
-          kubectl rollout status deployment/coin-service --timeout=10m
+          services=("notification-service" "user-service" "watchlist-service" "coin-service")
+          failed_services=()
+
+          for service in "${services[@]}"; do
+            if ! kubectl rollout status deployment/$service --timeout=10m; then
+              failed_services+=($service)
+            fi
+          done
+
+          if [ ${#failed_services[@]} -ne 0 ]; then
+            echo "Deployment failed for the following services: ${failed_services[@]}"
+            exit 1
+          else
+            echo "All services deployed successfully!"
+          fi
 
       # Step 15: Rollback deployment if any service fails
-      - name: Rollback All Services if Unsuccessful
+      - name: Rollback Failed Services
         if: failure()
         run: |
-          kubectl rollout undo deployment/notification-service
-          kubectl rollout undo deployment/user-service
-          kubectl rollout undo deployment/watchlist-service
-          kubectl rollout undo deployment/coin-service
-      
+          for service in "${failed_services[@]}"; do
+            kubectl rollout undo deployment/$service
+            echo "Rolled back $service due to failed deployment"
+          done
+
       # Step 16: Clean up
       - name: Clean up
         run: |
